### ISSUE TITLE
Bot down

### ISSUE THREAD

**Issue by Krinkle** [Krinkle/pywiki-fileprotectionsync#16]
As reported by @anticompositenumber on Commons ([link](https://commons.wikimedia.org/w/index.php?title=User_talk:Krinkle&oldid=605704638#Krinklebot_not_running)).

```shell
tools.krinklebot at tools-sgebastion-07.tools.eqiad.wmflabs in ~


$ tail -n100 fileprotectionsync.err 
  File "/data/project/krinklebot/src/pywiki-fileprotectionsync/fileprotectionsync.py", line 95, in <module>
    main()
  File "/data/project/krinklebot/src/pywiki-fileprotectionsync/fileprotectionsync.py", line 45, in main
    pywikibot.Page(commons_site, wiki['targetpage']).put(wt, config.editsummary)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/tools/__init__.py", line 1737, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/tools/__init__.py", line 1737, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/page.py", line 1361, in put
    **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/tools/__init__.py", line 1737, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/tools/__init__.py", line 1737, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/page.py", line 1283, in save
    cc=apply_cosmetic_changes, quiet=quiet, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/page.py", line 129, in wrapper
    handle(func, self, *args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/page.py", line 108, in handle
    func(self, *args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/page.py", line 1294, in _save
    watch=watch, bot=botflag, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/site.py", line 1323, in callee
    return fn(self, *args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/site.py", line 5168, in editpage
    token = self.tokens['edit']
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/site.py", line 1784, in __getitem__
    key = self.site.validate_tokens([key])[0]
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/site.py", line 3459, in validate_tokens
    'token')['type']
TypeError: 'NoneType' object is not subscriptable
CRITICAL: Exiting due to uncaught exception <class 'TypeError'>
Logging in to commons:commons as KrinkleBot@Autoprotect
Traceback (most recent call last):
  File "/data/project/krinklebot/src/pywiki-fileprotectionsync/fileprotectionsync.py", line 95, in <module>
    main()
  File "/data/project/krinklebot/src/pywiki-fileprotectionsync/fileprotectionsync.py", line 45, in main
    pywikibot.Page(commons_site, wiki['targetpage']).put(wt, config.editsummary)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/tools/__init__.py", line 1737, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/tools/__init__.py", line 1737, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/page.py", line 1361, in put
    **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/tools/__init__.py", line 1737, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/tools/__init__.py", line 1737, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/page.py", line 1283, in save
    cc=apply_cosmetic_changes, quiet=quiet, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/page.py", line 129, in wrapper
    handle(func, self, *args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/page.py", line 108, in handle
    func(self, *args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/page.py", line 1294, in _save
    watch=watch, bot=botflag, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/site.py", line 1323, in callee
    return fn(self, *args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/site.py", line 5168, in editpage
    token = self.tokens['edit']
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/site.py", line 1784, in __getitem__
    key = self.site.validate_tokens([key])[0]
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/site.py", line 3459, in validate_tokens
    'token')['type']
TypeError: 'NoneType' object is not subscriptable
CRITICAL: Exiting due to uncaught exception <class 'TypeError'>
Logging in to commons:commons as KrinkleBot@Autoprotect
Traceback (most recent call last):
  File "/data/project/krinklebot/src/pywiki-fileprotectionsync/fileprotectionsync.py", line 95, in <module>
    main()
  File "/data/project/krinklebot/src/pywiki-fileprotectionsync/fileprotectionsync.py", line 45, in main
    pywikibot.Page(commons_site, wiki['targetpage']).put(wt, config.editsummary)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/tools/__init__.py", line 1737, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/tools/__init__.py", line 1737, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/page.py", line 1361, in put
    **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/tools/__init__.py", line 1737, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/tools/__init__.py", line 1737, in wrapper
    return obj(*__args, **__kw)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/page.py", line 1283, in save
    cc=apply_cosmetic_changes, quiet=quiet, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/page.py", line 129, in wrapper
    handle(func, self, *args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/page.py", line 108, in handle
    func(self, *args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/page.py", line 1294, in _save
    watch=watch, bot=botflag, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/site.py", line 1323, in callee
    return fn(self, *args, **kwargs)
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/site.py", line 5168, in editpage
    token = self.tokens['edit']
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/site.py", line 1784, in __getitem__
    key = self.site.validate_tokens([key])[0]
  File "/mnt/nfs/labstore-secondary-tools-project/krinklebot/src/pywikibot-core/pywikibot/site.py", line 3459, in validate_tokens
    'token')['type']
TypeError: 'NoneType' object is not subscriptable
CRITICAL: Exiting due to uncaught exception <class 'TypeError'>
```

**Comment by legoktm** [comment]
Fixed, just needed an update to Pywikibot (now running 6.6.1). I also had to remove the legacy `sysopnames` from user-config.py, it's no longer needed.
